let product_name = [
  {
    name: "GH Bass & Co Black Shoes",
    img_url1: "images/for_sale_yes/GH_Bass&Co_Black_Shoes/IMG_2994-min.JPG",
    img_url2: "images/for_sale_yes/GH_Bass&Co_Black_Shoes/IMG_2997-min.JPG",
    img_url3: "images/for_sale_yes/GH_Bass&Co_Black_Shoes/IMG_2998-min.JPG",
    img_url4: "images/for_sale_yes/GH_Bass&Co_Black_Shoes/IMG_3000-min.JPG",
    price: "$" + 39,
    description: "GH Bass & Co Black Shoes",
    used: "used",
  },
  {
    name: "Alfa Network",
    img_url1: "images/for_sale_yes/Alfa_Network/IMG_2876-min.JPG",
    img_url2: "images/for_sale_yes/Alfa_Network/IMG_2867-min.JPG",
    img_url3: "images/for_sale_yes/Alfa_Network/IMG_2874-min.JPG",
    img_url4: "images/for_sale_yes/Alfa_Network/IMG_2871-min.JPG",
    price: "$" + 24,
    description:
      "AWUS036NH 802.11 b/g/n Long-Range USB Adapter 5db Antenna. Superior Wi-Fi Performance Professionally Tuned Wireless, Better Range & CoverageIncreased Bandwidth, More Applications Increased Wireless Signal Penetration",
    used: "used",
  },
  {
    name: "Sony Professional Headset",
    img_url1: "images/for_sale_yes/Headset/IMG_1695.jpg",
    img_url2: "images/for_sale_yes/Headset/IMG_1696.jpg",
    img_url3: "images/for_sale_yes/Headset/IMG_1697.jpg",
    img_url4: "images/for_sale_yes/Headset/IMG_1724.jpg",
    price: "$" + 75,
    description: "Sony Professional Headset with case",
    used: "used",
  },
  {
    name: "Tripod Dolica",
    img_url1: "images/for_sale_yes/Tripod/tripod4.jpeg",
    img_url2: "images/for_sale_yes/Tripod/tripod2.jpeg",
    img_url3: "images/for_sale_yes/Tripod/tripod1.jpeg",
    img_url4: "images/for_sale_yes/Tripod/tripod3.jpeg",
    price: "$" + 23,
    description: "Tripod Dolica",
    used: "used",
  },
  {
    name: "Vr Goggles",
    img_url1: "images/for_sale_yes/VR_Goggles/vr_goggles.jpeg",
    img_url2: "images/for_sale_yes/VR_Goggles/vr_goggles1.jpeg",
    img_url3: "images/for_sale_yes/VR_Goggles/vr_goggles2.jpeg",
    img_url4: "images/for_sale_yes/VR_Goggles/vr_goggles3.jpeg",
    price: "$" + 16,
    description: "Vr Goggles",
    used: "used",
  },
  {
    name: "Onitsuka Tiger White",
    img_url1: "images/for_sale_yes/Onitsuka_Tiger/IMG_2991.JPG",
    img_url2: "images/for_sale_yes/Onitsuka_Tiger/IMG_2990.JPG",
    img_url3: "images/for_sale_yes/Onitsuka_Tiger/IMG_2987.JPG",
    img_url4: "images/for_sale_yes/Onitsuka_Tiger/IMG_2993.JPG",
    price: "$" + 16,
    description: "Onitsuka Tiger White",
    used: "used",
  },
];
